name: Sync Fork virtual-event-starter-kit1

on:
  push:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click
  
jobs:
  update_external_airflow_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.PAT }}
          upstream_repository: HsiangNianian/virtual-event-starter-kit1
          target_repository: retrofor/virtual-event-starter-kit1
          upstream_branch: main
          target_branch: main
          force: true
          tags: true
