name: Sync Fork 

on:
  push:
  schedule:
    - cron: '*/5 * * * *' # every 30 minutes
  workflow_dispatch: # on button click
  
jobs:
  sync-repos:
    runs-on: ubuntu-latest
    steps:
      - name: OlivaDiceCore
        uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.CI_TOKEN }}
          upstream_repository: OlivOS-Team/OlivaDiceCore
          target_repository: HydroRoll-Team/OlivaDiceCore
          upstream_branch: main
          target_branch: main
          force: true
          tags: true
      - name: sealdice-core
        uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.CI_TOKEN }}
          upstream_repository: sealdice/sealdice-core
          target_repository: HydroRoll-Team/sealdice-core
          upstream_branch: master
          target_branch: master
          force: true
          tags: true
      - name: Dice
        uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.CI_TOKEN }}
          upstream_repository: Dice-Developer-Team/Dice
          target_repository: HydroRoll-Team/Dice
          upstream_branch: newdev
          target_branch: newdev
          force: true
          tags: true
      - name: SinaNya
        uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.CI_TOKEN }}
          upstream_repository: SitaNya/SinaNya
          target_repository: HydroRoll-Team/SinaNya
          upstream_branch: master
          target_branch: master
          force: true
          tags: true
      - name: DiceParser
        uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.CI_TOKEN }}
          upstream_repository: Rolisteam/DiceParser
          target_repository: HydroRoll-Team/DiceParser
          upstream_branch: master
          target_branch: cpp
          force: true
          tags: true
      - name: nonebot-dicepp
        uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.CI_TOKEN }}
          upstream_repository: pear-studio/nonebot-dicepp
          target_repository: HydroRoll-Team/nonebot-dicepp
          upstream_branch: master
          target_branch: master
          force: true
          tags: true
      - name: ergo
        uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.CI_TOKEN }}
          upstream_repository: ergochat/ergo
          target_repository: HydroRoll-Team/ergo
          upstream_branch: master
          target_branch: master
          force: true
          tags: true
      - name: dicer
        uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.CI_TOKEN }}
          upstream_repository: unvisitor/dicer
          target_repository: HydroRoll-Team/dicer
          upstream_branch: master
          target_branch: master
          force: true
          tags: true
      - name: Quantumix
        uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.CI_TOKEN }}
          upstream_repository: noctisynth/Quantumix
          target_repository: HydroRoll-Team/Quantumix
          upstream_branch: main
          target_branch: main
          force: true
          tags: true
      - name: Moonstone
        uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.CI_TOKEN }}
          upstream_repository: noctisynth/Moonstone
          target_repository: HydroRoll-Team/Moonstone
          upstream_branch: main
          target_branch: main
          force: true
          tags: true
      - name: diceutils
        uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.CI_TOKEN }}
          upstream_repository: noctisynth/diceutils
          target_repository: HydroRoll-Team/diceutils
          upstream_branch: main
          target_branch: main
          force: true
          tags: true
      - name: diceutils
        uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.CI_TOKEN }}
          upstream_repository: noctisynth/yggdrasil
          target_repository: HydroRoll-Team/yggdrasil
          upstream_branch: main
          target_branch: main
          force: true
          tags: true
