name: Sync Forks

on:
  push:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 执行

jobs:
  dispatch:
    strategy:
      matrix:
        repo: ['retrofor/Dice', 'retrofor/OlivOS', 'retrofor/virtual-event-starter-kit1']
        src_repo: ['Dice-Developer-Team/Dice', 'OlivOS-Team/OlivOS', 'HsiangNianian/virtual-event-starter-kit1']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
        with:
          repository: ${{ matrix.repo }}
          token: ${{ secrets.PAT }}
      - name: Sync files with dst-octocat-repsotiory!
        uses: denis-tingajkin/sync-files@main
        with:
          git-author-email: 'octocat@github.com'
          git-author-name: 'Octocat'
          src-repository: ${{ matrix.src_repo }}
