name: Sync Forks

on:
  push:
  
  schedule:
    - cron: '0 0 * * *' # 每天UTC时间00:00自动执行

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git config
        run: |
          git config --global user.email "admin@jyunko.cn"
          git config --global user.name "HsiangNianian"

      # 自定义需要同步的原仓库分支以及现组织名下的仓库分支
      - name: Sync forked repositories
        run: |
          REPOS="OlivOS-Team/OlivOS,Dice-Developer-Team/Dice" # 需要同步的仓库列表，用逗号分隔
          BRANCHES="main:main,newdev:newdev" # 分支映射关系，用冒号分隔
          for REPO in $(echo $REPOS | sed "s/,/ /g")
          do
            echo "Syncing $REPO..."
            UPSTREAM=$(echo $REPO | awk -F/ '{print $1}')
            FORK=$(echo $REPO | awk -F/ '{print $2}')
            git clone https://github.com/$UPSTREAM/$FORK.git --depth 1
            cd $FORK
            git remote add upstream https://github.com/$UPSTREAM/$FORK.git
            git fetch upstream
            for PAIR in $(echo $BRANCHES | sed "s/,/ /g")
            do
              UPSTREAM_BRANCH=$(echo $PAIR | awk -F: '{print $1}')
              ORG_BRANCH=$(echo $PAIR | awk -F: '{print $2}')
              git checkout $ORG_BRANCH || git checkout -b $ORG_BRANCH
              git merge upstream/$UPSTREAM_BRANCH --allow-unrelated-histories -m "Merge upstream branch $UPSTREAM_BRANCH"
            done
            git push origin --all
            cd ..
            rm -rf $FORK
          done
