name: Sync Forks for virtual-event-starter-kit1

on:
  push:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 执行

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
        with:
          repository: retrofor/virtual-event-starter-kit1
          token: ${{ secrets.PAT }}
      - name: Sync files with virtual-event-starter-kit1!
        uses: denis-tingajkin/sync-files@main
        with:
          git-author-email: 'admin@jyunko.cn'
          git-author-name: 'HsiangNianian'
          src-repository: retrofor/virtual-event-starter-kit1

