name: Sync Forks

on:
  push:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 执行

jobs:
  dispatch:
    strategy:
      matrix:
        repo: ['retrofor/Dice', 'retrofor/OlivOS', 'retrofor/virtual-event-starter-kit1']
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ matrix.repo }}
          event-type: synchronize
