name: Sync Forks

on:
  push:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 执行

jobs:
  dispatch:
    strategy:
      matrix:
        repo: ['retrofor/Dice', 'retrofor/OlivOS', 'retrofor/virtual-event-starter-kit1']
        src_repo: ['Dice-Developer-Team/Dice', 'OlivOS-Team/OlivOS', 'HsiangNianian/virtual-event-starter-kit1']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
        with:
          repository: retrofor/Dice #${{ matrix.repo }}
          token: ${{ secrets.PAT }}
      - name: Sync files with Dice!
        uses: denis-tingajkin/sync-files@main
        with:
          git-author-email: 'admin@jyunko.cn'
          git-author-name: 'HsiangNianian'
          src-repository: Dice-Developer-Team/Dice #${{ matrix.src_repo }}
      - name: Checkout files
        uses: actions/checkout@v2
        with:
          repository: retrofor/OlivOS #${{ matrix.repo }}
          token: ${{ secrets.PAT }}
      - name: Sync files with OlivOS!
        uses: denis-tingajkin/sync-files@main
        with:
          git-author-email: 'admin@jyunko.cn'
          git-author-name: 'HsiangNianian'
          src-repository: OlivOS-Team/OlivOS #${{ matrix.src_repo }}
      - name: Checkout files
        uses: actions/checkout@v2
        with:
          repository: retrofor/virtual-event-starter-kit1 #${{ matrix.repo }}
          token: ${{ secrets.PAT }}
      - name: Sync files with virtual-event-starter-kit1!
        uses: denis-tingajkin/sync-files@main
        with:
          git-author-email: 'admin@jyunko.cn'
          git-author-name: 'HsiangNianian'
          src-repository: HsiangNianian/virtual-event-starter-kit1 #${{ matrix.src_repo }}
