name: Sync Forks

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  sync-forks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Configure Git
      run: |
        git config --global user.name "HsiangNiania"
        git config --global user.email "HsiangNianian@outlook.com"
        git config --global pull.rebase true
    
    - name: Sync forks
      run: |
        ORGANIZATION_NAME=retrofor # Replace with your organization name
        REPO_BRANCHES=(OlivOS-Team/main upstream/newdev) # Replace with the branches you want to sync
        for REPO_NAME in $(curl -s https://api.github.com/orgs/$ORGANIZATION_NAME/repos | jq -r '.[].name'); do
          if [[ $REPO_NAME != "$GITHUB_REPOSITORY_NAME" ]]; then
            git clone https://github.com/$ORGANIZATION_NAME/$REPO_NAME.git
            cd $REPO_NAME
            git remote add upstream https://github.com/$(echo $REPO_NAME | sed 's/-/_/')/$(echo $REPO_NAME | sed 's/-/./').git
            git fetch upstream
            for BRANCH in "${REPO_BRANCHES[@]}"; do
              git checkout $BRANCH
              git merge upstream/$BRANCH --no-edit
            done
            git push origin $REPO_BRANCHES[0]
            cd ..
            rm -rf $REPO_NAME
          fi
        done
    
    - name: Create issue if sync failed
      if: always()
      run: |
        if [ $? -ne 0 ]; then
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d "{\"title\":\"Repository sync status\",\"body\":\"There was an error syncing the repositories.\"}"
        fi
