name: Sync Forks

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 执行
    
  push:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: OlivOS
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.PAT }}
        repository: retrofor/OlivOS
        event-type: sync
    - name: Dice
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.PAT }}
        repository: retrofor/Dice
        event-type: sync
    - name: virtual-event-starter-kit1
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.PAT }}
        repository: retrofor/virtual-event-starter-kit1
        event-type: sync
