name: Sync Forks

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 执行
    
  push:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Git user
        run: |
          git config --global user.name "HsiangNianian"
          git config --global user.email "HsiangNianian@outlook.com"

      - name: Sync Forks
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_SECRET }}
        run: |
          org_name=retrofor

          # 设置需要同步的 fork 仓库名称，用空格隔开
          fork_repos="OlivOS Dice"

          for repo in $fork_repos; do
            upstream_url=$(curl -s https://api.github.com/repos/$org_name/$repo | jq -r '.parent.clone_url')
            git clone --depth=1 $upstream_url /tmp/$repo
            cd /tmp/$repo
            git remote add upstream $upstream_url
            git fetch upstream

            for branch in $(git branch -r | grep upstream); do
              local_branch=${branch#upstream/}
              git checkout $local_branch || git checkout -b $local_branch
              git merge --no-edit $branch
              git push origin $local_branch
            done

            cd -
          done
